spring.application.name=Street-Alert

aws.secretsmanager.region=ap-south-1
aws.secretsmanager.secret-name=prod/app/newsAPI
aws.secretsmanager.api-key-field=apiKey

spring.datasource.url=jdbc:postgresql://localhost:5432/market
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Server
server.port=8080

security.jwt.secret=SomeRandomShitIWroteWhileMakingThisApp
security.jwt.expiration-ms=86400000
